Global:
  device: gpu
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output_new_visualC3_textline/crnn_ctc/
  save_epoch_step: [1, 25]
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  eval_epoch_step: [0, 1]
  cal_metric_during_train: False
  pretrained_model: ./output_new_visualC3_textline/crnn_ctc/best.pth
  checkpoints:
  use_tensorboard: false
  infer_img:
  # for data or label process
  character_dict_path: &character_dict_path ./tools/utils/ppocr_keys_v1.txt # ch
  max_text_length: &max_text_length 300
  use_space_char: &use_space_char True
  save_res_path: ./output_new_visualC3_textline/crnn_ctc/predicts_crnn_ctc.txt
  use_amp: True

Optimizer:
  name: AdamW
  lr: 6.5e-4 # for 4gpus bs256/gpu
  weight_decay: 0.05
  filter_bias_and_bn: False

LRScheduler:
  name: OneCycleLR
  warmup_epoch: 5
  cycle_momentum: False

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Encoder:
    name: ResNet_ASTER
  Decoder:
    name: CTCDecoder

Loss:
  name: CTCLoss
  zero_infinity: True

PostProcess:
  name: CTCLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

Metric:
  name: RecMetric
  main_indicator: acc
  # is_filter: True

Train:
  dataset:
    name: LMDBDataSet
    data_dir: /a800data1/lirunrui/lmdb_output/new_Visual_C3_textline/train/
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - PARSeqAugPIL:
      - CTCLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - RecTVResize:
          image_shape: [32, 512]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: &batch_size_per_card 64
    drop_last: True
    num_workers: 16

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: /a800data1/lirunrui/lmdb_output/new_Visual_C3_textline/test_correct/
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - CTCLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - RecTVResize:
          image_shape: [32, 512]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: *batch_size_per_card
    num_workers: 16
